### ISSUE TITLE
On grommet.io the "start coding" section, there playground code has a bunch of white space after the code sample

### ISSUE THREAD

**Issue by ShimiSun** [grommet/grommet-site#112]
From @L0ZZI 
https://github.com/grommet/grommet-docs/issues/320

**Comment by spencerkordecki** [comment]
@ShimiSun Turns out this is a default setting in Monaco Editor, but there's a flag to disable it which makes it so there's only as much space in the editor as there is code, and then expands as necessary. I'm opening up a PR now with the change!
