### ISSUE TITLE
Accordion/Chart have multiple 'components' listed on their page

### ISSUE THREAD

**Issue by taysea** [grommet/grommet-site#122]
When I scroll down past the initial set of prop/theme definitions for Chart, I see a second section also labelled "Chart" but with a different description and no additional props.

When I do the same of Accordion, I see a section another section titled Accordion but this refers to an accordion panel. I didn't even know if was there because I wouldn't expect 2 'components' on one page. Would it make sense for Accordion Panel to have its own page? Or if not, how can we indicate that there is more info about accordion panel because I came across this purely on accident when I did a big scroll.

**Comment by ShimiSun** [comment]
Yea, good catch.
The Heading below the Chart should be Calc. and below Accordion it's Accordion Panel, its a recent regression, mind taking a look?
