### ISSUE TITLE
Website doesnt build at all.

### ISSUE THREAD

**Issue by GodrieMaxime** [grommet/grommet-site#155]
The NPM run start does not work and the website isn't building.

                                                                                                                                 
ERROR in ./node_modules/monaco-editor/esm/vs/editor/editor.api.js                                                                
Module build failed (from ./node_modules/monaco-editor-webpack-plugin/loaders/include.js):                                       
TypeError: loaderUtils.getOptions is not a function                                                                              
    at Object.pitch (C:\projects\React\grommet-site-master\node_modules\monaco-editor-webpack-plugin\loaders\include.js:4:68)    
 @ ./node_modules/react-monaco-editor/lib/editor.js 8:37-86                                                                      
 @ ./node_modules/react-monaco-editor/lib/index.js                                                                               
 @ ./src/components/Doc/MonacoEditor.js                                                                                          
 @ ./src/screens/Home/Start.js                                                                                                   
 @ ./src/screens/Home/index.js                                                                                                   
 @ ./src/components/Content.js                                                                                                   
 @ ./src/App.js                                                                                                                  
 @ ./src/index.js

**Comment by GodrieMaxime** [comment]
WARNING in ./node_modules/monaco-editor/esm/vs/language/typescript/lib/typescriptServices.js
    Module not found: Error: Can't resolve '@microsoft/typescript-etw' in 'C:\projects\React\grommet-site-master\node_modules\monaco-editor\esm\vs\language\typescript\lib'
     @ ./node_modules/monaco-editor/esm/vs/language/typescript/lib/typescriptServices.js
     @ ./node_modules/monaco-editor/esm/vs/language/typescript/tsWorker.js
     @ ./node_modules/monaco-editor/esm/vs/language/typescript/ts.worker.js

**Comment by ShimiSun** [comment]
Checkout you are using npm version that is older than 12.

and run 
```
rm -rf yarn.lock
rm -rf package-lock.json
rm -rf node_modules
yarn cache clean
yarn install
yarn start
```

That should do the trick.

**Comment by ShimiSun** [comment]
Thanks for sharing @mikeruddy !
