### ISSUE TITLE
Layer sizing

### ISSUE THREAD

**Issue by atanasster** [grommet/grommet-site#16]
https://v2.grommet.io/photo-browser 
click in an image
The layer is not full-screen, and also the image is not centered (small image in the top left corner)
![screenshot657](https://user-images.githubusercontent.com/6075606/36077480-6a08cdba-0f39-11e8-8b80-088cfcdc3bb4.jpg)

**Comment by ShimiSun** [comment]
Thanks @atanasster for filing the issue. closing due to the removal of photo-browser
