### ISSUE TITLE
Links to archived repos

### ISSUE THREAD

**Issue by OlivierJM** [grommet/grommet-site#183]
First of all, I want to appreciate your effort to make this awesome library

The links on the home page currently go to the repos that are archived, one example comes from here https://github.com/grommet/grommet-site/blob/master/src/screens/Home/Start.js#L77 and this https://github.com/grommet/grommet-site/blob/master/src/screens/Home/Start.js#L84 

Was this intentional? If not are there other links that can be used instead of these?

**Comment by ShimiSun** [comment]
We are welcoming contributions to fix the links :)

**Comment by OlivierJM** [comment]
I was trying to look for the correct links but I didn't find them, would you know where those repos were moved if they are now part of the main repo.

**Comment by ShimiSun** [comment]
@IanKBovard Can you please take a look at this issue?

**Comment by ShimiSun** [comment]
Thank you for bringing up the issue. The repos are no longer archived and still relevant for usage. The issue is fixed.

**Comment by OlivierJM** [comment]
Thanks @ShimiSun
