### ISSUE TITLE
Typo in the sample code for the <Form> component

### ISSUE THREAD

**Issue by tromgy** [grommet/grommet-site#190]
The sample code for the `<Form>` at https://v2.grommet.io/form component contains a typo:

```
<FormField name="name" htmlfor="text-input-id" label="Name">
```

The sample code should say:
```
<FormField name="name" htmlFor="text-input-id" label="Name">
```

The property should be spelled **htmlFor**, not **htmlfor**

![image](https://user-images.githubusercontent.com/12632548/103021019-7b4adc00-4517-11eb-9a8e-dfd28f4a4857.png)

**Comment by ShimiSun** [comment]
Looks like a straight forward contribution, feel free to make one.

**Comment by tromgy** [comment]
Yes, it should be trivial, except that `npm install` doesn't work, so I can't build/verify anything.

```
3277 error code ENOPACKAGEJSON
3278 error package.json Non-registry package missing package.json: grommet-theme-hpe@https://github.com/grommet/grommet-theme-hpe/tarball/NEXT-stable.
```

I downloaded both **NEXT-stable** and **stable** directly, and neither has **package.json**

**Comment by ShimiSun** [comment]
Happy 2021! 
Installation should be good now, PR https://github.com/grommet/grommet-site/pull/191. let me know how it goes.

**Comment by tromgy** [comment]
Thanks, @ShimiSun, looking at your change I now realize that this project is yarn-based, so one has to use `yarn install` rather than `npm install`. With this command it works. I'm also going to update **README.md** to remove the reference to `npm install`, as it will confuse people like it did for me.
