### ISSUE TITLE
Grommet Docs is Broken 

### ISSUE THREAD

**Issue by MikeWalrath** [grommet/grommet-site#197]
Notified by https://twitter.com/BaseDefined/status/1348482693093339136

Users are unable to search and the code examples are not working.

**Comment by ericsoderberghp** [comment]
![Screen Shot 2021-01-11 at 9 01 40 AM](https://user-images.githubusercontent.com/11637956/104213870-9fe5f580-53eb-11eb-8e08-0a83cfb30473.png)

might be related as well

**Comment by resynth1943** [comment]
Ahh, so that's why it's been acting up :thinking: good find, thanks! Will subscribe myself to this issue -- if any help is needed, please reach out :-)

**Comment by resynth1943** [comment]
Is it possible that [this](https://github.com/grommet/grommet-site/commit/7147e5b9429245674767fdd6f5428aa8e6404629) broke the app? I remember it working fine before that. I'll test this tomorrow.
