### ISSUE TITLE
Cannot install from package.json

### ISSUE THREAD

**Issue by tromgy** [grommet/grommet-site#206]
### Reproduction:

1. Clone: `git clone https://github.com/grommet/grommet-site.git`
2. Install: `yarn install`

The latter command fails:

```
yarn install v1.22.10
[1/5] Validating package.json...
[2/5] Resolving packages...
warning Resolution field "react-side-effect@2.1.0" is incompatible with requested version "react-side-effect@^1.1.0"
[3/5] Fetching packages...
error https://github.com/grommet/grommet/tarball/stable: Integrity check failed for "grommet" (computed integrity doesn't match our records, got "sha512-2hJ6JKfccZTzDeuozTI/qHmN3r+1fnEaDTtx76PneQdUlW7pReu5AwdBLAk2Vdb5qpSUBZIH+H0vzc8Og3fczQ== sha1-09R3HGKeDe31VQxb987hUCVSjqk=")
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

Tried on two different systems: 

- macOS Big Sur 11.2, Node v14.15.1, yarn 1.22.5
- Ubuntu Bionic Beaver 18.04.5, Node 12.20.0, yarn 1.22.10

It fails the same way.

**Comment by halocline** [comment]
This occurs because grommet-site is referencing the latest stable branch of grommet. As new commits are added to the stable branch, the sha hash gets updated and becomes out of sync with the sha in the yarn.lock file.

To fetch the latest grommet stable, remove yarn.lock and clean yarn cache, then yarn install.
```
rm yarn.lock && yarn cache clean && yarn install
```

**Comment by tromgy** [comment]
maybe this info should be added to **README.md**?

**Comment by tromgy** [comment]
I've just tried it and it worked. Thanks!

**Comment by ShimiSun** [comment]
@tromgy thanks for the feedback, I've updated the README file with the above information.
