### ISSUE TITLE
Better WorldMap onSelectPlace

### ISSUE THREAD

**Issue by dgennetten** [grommet/grommet-site#23]
The current onSelectPlace example (Sydney) is easy to miss (I was going to submit 'let's add an onSelectPlace example' until I saw it in the code...then noticed it on the map).  I believe it would be more noticeable if it were 1) higher contrast, and 2) somewhere mid-continent.

(As a bit of an easter egg, we could move it around to follow a current event.)

**Comment by ShimiSun** [comment]
Thanks @dgennetten ! the example was changed in the new grommet site. feel free to file new issue if you are still able to reproduce.
