### ISSUE TITLE
The start reading link leads to a blank page but refreshing shows page correctly

### ISSUE THREAD

**Issue by conorhastings** [grommet/grommet-site#27]
![grommetv2startreading](https://user-images.githubusercontent.com/8263298/44800056-719d4d80-ab83-11e8-9762-9c0179a88e5a.gif)

**Comment by spencerkordecki** [comment]
@conorhastings I opened a PR for this, should be fixed next time a release is made!

**Comment by alansouzati** [comment]
thanks for the PR @spencerkordecki
