### ISSUE TITLE
Grommet Site Content Update

### ISSUE THREAD

**Issue by jcfilben** [grommet/grommet-site#346]
- [x] Site home page doesn’t pass accessibility checks.
- [x] Remove reference to [Grommet Design Kit](https://github.com/grommet/design-kit) under “and start designing” section. Grommet Design Kit is outdated and not maintained. We can potentially replace with a link to the Grommet Designer.
- [x] The [accessibility demo](https://vimeo.com/187068246) Vimeo link under the “don’t take our word for it” is no longer working (not sure if the video still exists or is still relevant) but we should consider removing this.
- [x] Grommet Designer and Themer should no longer be labeled as ‘beta’.
- [ ] The [theming documentation](https://github.com/grommet/grommet/wiki/Grommet-v2-theming-documentation) currently on the grommet repository wiki should be moved to the site and possible enhanced.

**Comment by ericsoderberghp** [comment]
The site now scores 100 for accessibility in Lighthouse.

**Comment by ericsoderberghp** [comment]
Letting the theme documentation task be dealt with separately.
