### ISSUE TITLE
External links not working

### ISSUE THREAD

**Issue by mtendotnet** [grommet/grommet-site#35]
The external links (github, slack, storybook, twitter) aren't working on the home page. Noticed that the `<Button as="a" href="...">` components are being rendered as `<button>`s instead of `<a>` tags.

```
<button class="StyledButton-sc-323bzc-0 hnsXoe" as="a" aria-label="Go to Github" href="https://github.com/grommet/grommet/tree/NEXT">
  <div class="StyledBox-sc-13pk1d4-0 ksxcgD">GitHub</div>
</button>
```

Updating `styled-components` dependency from `v3` to `v4` fixes this. Will create PR for this.

**Comment by alansouzati** [comment]
thanks martin makes sense. a PR is gladly appreciated!
