### ISSUE TITLE
Video - missing `controls` custom type

### ISSUE THREAD

**Issue by ShimiSun** [grommet/grommet-site#367]
Hi! Thanks for this fun feature @jlaluces123! 
Is there any work in progress regarding the updated documentation of the new `controls` customization? 
It will be great to let the users know about this feature.

_Originally posted by @ShimiSun in https://github.com/grommet/grommet/issues/5689#issuecomment-1079837177_

**Comment by jcfilben** [comment]
Closing since https://github.com/grommet/grommet-site/pull/368 has been merged
