### ISSUE TITLE
Add link to HPE Design System docs to component pages

### ISSUE THREAD

**Issue by taysea** [grommet/grommet-site#397]
builds off of #402 

Right now, there is low awareness about how to transition from Grommet docs to HPE Design System guidance on a component. In order to raise visibility of HPE Design System docs and examples, a link should be added to each component page (alongside the Storybook, CodeSandbox, Github links) that leads to the Design System guidance for that component.

Deliverables:
- [ ] Adjust site layout to allow for "Design System Guidance" link when on HPE theme (tbd on label)
- [ ] Add links to each component page

**Comment by ericsoderberghp** [comment]
I think we should do this only when the theme is `hpe`. And, we might want to consider making it easier to switch the theme of the grommet documents as well.

**Comment by JCoder121** [comment]
After meeting with Jessica, I will first work on different prototypes for an easier way to toggle between themes. We will evaluate these prototypes and then move forward with adding links to HPE Design System docs to components page.

**Comment by JCoder121** [comment]
Currently most updated direction: see #405.
