### ISSUE TITLE
Add clearer way to switch theme and "Use for HPE"

### ISSUE THREAD

**Issue by taysea** [grommet/grommet-site#402]
There is certain information that we'd like to reveal to HPE users on the grommet site without cluttering the grommet docs with HPE relevant information. Therefore, we should add a way to more clearly switch grommet site to a mode of "Use for HPE" or "Use for Open Source"

Deliverables:
- [x] Add theme switcher to "Use for HPE"
- [x] Add functionality where previously selected theme is stored in a cookie (similar to DS site w light/dark mode)

**Comment by JCoder121** [comment]
Related PRs:
https://github.com/grommet/grommet-site/pull/399
https://github.com/grommet/grommet-site/pull/400
https://github.com/grommet/grommet-site/pull/401

**Comment by JCoder121** [comment]
Closed as we are not yet moving forward with theme switcher button in head navigation bar. Could be opened/branched in the future.
