### ISSUE TITLE
Header documentation has incorrect sticky prop value

### ISSUE THREAD

**Issue by CopyJosh** [grommet/grommet-site#475]
`Header` component documentation incorrectly references the `scrollup` value of the `sticky` prop.

In the screenshot observe `sticky = "scrollUp"` should be all lowercase, `sticky = "scrollup"` as referenced in the code, 

```js
if (target && sticky === 'scrollup')
```

![Screenshot 2023-05-23 at 11 41 48 AM](https://github.com/grommet/grommet-site/assets/919738/94969673-d24a-46cc-8394-2ad099f7b37d)

Thanks!

**Comment by jcfilben** [comment]
Thanks for reporting this issue! I just created a pull request to get this resolved
