### ISSUE TITLE
Build Fail.

### ISSUE THREAD

**Issue by dgennetten** [grommet/grommet-site#49]
When running local, I get:

ERROR in ./node_modules/monaco-editor/esm/vs/editor/editor.main.js
Module build failed (from ./node_modules/monaco-editor-webpack-plugin/loaders/include.js):
TypeError: loaderUtils.getOptions is not a function

**Comment by ShimiSun** [comment]
Let me know if you still see this error after our quick troubleshooting this morning. Although it is a little different than the error we discussed.

**Comment by dgennetten** [comment]
Thanks for your help @ShimiSun!  It looks good.

**Comment by moecre** [comment]
Hi guys,
what was the problem here? I have the same issue on a freshly cloned version.
Best,
Pat

**Comment by ShimiSun** [comment]
try to delete all lock files and yarn cache. 
`rm -rf node_modules`
`rm -rf yarn.lock`
`rm -rf package-lock.json`
`yarn cache clean`
`yarn install`
