### ISSUE TITLE
minor - '/use' page 

### ISSUE THREAD

**Issue by ShimiSun** [grommet/grommet-site#50]
https://v2.grommet.io/use

Needs to remove grommet-cli references. not used in v2.

@ericsoderberghp before I'll remove it, I wanted your opinion whether we want to mention any other resources here that might be relevant for v2.

**Comment by crashuniverse** [comment]
I was looking at this one, and looks like #98 certainly fixes this.

**Comment by ShimiSun** [comment]
Yep!! Thank you for communicating
