### ISSUE TITLE
Clarify if grommet is still support mobile first or not.

### ISSUE THREAD

**Issue by Sulaymon333** [grommet/grommet-site#502]
According to grommet site, it is mentioned that grommet is **mobile first**. I don't know if grommet still hold on to this approach. I have experienced one or two issues using site developed with grommet on a mobile device. 

Do we still have the philosophy of grommet being mobile first react component library? Otherwise, we might need to update the website to have a consistent message to consumers of grommet

Screenshot from grommet site
![image](https://github.com/grommet/grommet-site/assets/28514231/9b4d2619-0f69-4f47-995f-585ddac64019)

**Comment by jcfilben** [comment]
Hey good question, Grommet does still have a mobile-first philosophy. Can you share the issues you were experiencing with Grommet on a mobile device?

**Comment by Sulaymon333** [comment]
Hi Thank you for your response. Please see the screenshots attached below for issues I face while using GLCP website built with Grommet on the mobile.


  <div>
    <p><strong>Short header vs body</strong></p>
    <img height='700px' src='https://github.com/grommet/grommet-site/assets/28514231/aa00e5d0-a045-4252-9b3e-2a2385463f15'/> 
  </div>

  <div>
    <p><strong>Country list not searchable</strong></p>
    <img height='700px' src='https://github.com/grommet/grommet-site/assets/28514231/2f95a1fa-a653-4c4a-a290-01bbec1d1ef8'/>
  </div>

**Comment by jcfilben** [comment]
Thanks for sharing, these are likely implementation errors within the platform and not necessarily an issue with Grommet. However if you do think there is a Grommet issue with mobile environments feel free to file an issue on the Grommet repo with a codesandbox or code snippet that reproduces the issue.

**Comment by jcfilben** [comment]
Closing for now, feel free to file and follow on tickets as needed to flag any Grommet related mobile issues.
