### ISSUE TITLE
Simplify DNS and hosting to improve performance 

### ISSUE THREAD

**Issue by MikeWalrath** [grommet/grommet-site#52]

**Comment by oorestisime** [comment]
I am not sure if you have something in mind here or going, but i suggest and can help migrate to gatsby if you want (and then you choose a cdn, i worked with netlify already but people deploy on S3 or heroku or ...)

**Comment by crashuniverse** [comment]
What is the performance problem here - to make this thread more objective? @oorestisime

**Comment by oorestisime** [comment]
sorry i didn't mention anywhere performance. you d'have to ask @MikeWalrath :)

**Comment by crashuniverse** [comment]
Apologies, Sire :-) I completely misunderstood the source of report here. Thank you for tagging OP.

**Comment by ShimiSun** [comment]
I think we solved our DNS issues. closing.
