### ISSUE TITLE
Inertial scrolling is broken

### ISSUE THREAD

**Issue by bbhoss** [grommet/grommet-site#66]
I’m on iOS 12 mobile safari and scrolling has no inertia. Scrolling stops as soon as I release my finger rather than continuing with inertia as on other sites.

**Comment by ericsoderberghp** [comment]
I cannot seem to reproduce this. Is there a particular URL that is demonstrating this?

**Comment by bbhoss** [comment]
The main grommet site/front page does it for me: https://v2.grommet.io

If that’s working for you on the latest iOS I’m not sure why. This is the only page I’m having this issue with. I do have an ad-blocker but not sure it makes sense

**Comment by MikeWalrath** [comment]
@bbhoss I'm also not able to reproduce this issue. Do you mind double checking on your side?

**Comment by bbhoss** [comment]
Looks fixed to me.
