### ISSUE TITLE
Keyboard history navigation being swallowed

### ISSUE THREAD

**Issue by karatechops** [grommet/grommet-site#67]
Trying to navigate browser history with keyboard is being hijacked in Chrome. `cmd` + `<-` attempts to navigate then reloads the page. I'm assuming this is because there's an arrow listener to navigate pages, this behavior does not seem intuitive for the user.

**Comment by ericsoderberghp** [comment]
Fixed in ae580b2353f4e738220a11890fdb21243b313a66
