### ISSUE TITLE
Stale SEO data

### ISSUE THREAD

**Issue by karatechops** [grommet/grommet-site#78]
Currently if I search google for `grommet accordion` the first link is from the old docs. 

![screen shot 2019-02-05 at 11 08 03 am](https://user-images.githubusercontent.com/5983843/52286626-82be6780-2936-11e9-96b6-de39109f4847.png)

I noticed the current site does not utilize any server side rendering or SEO friendliness. Seeing as the site does not require full featured async SSR as the data is static, is there any discussion to add a static site generator to the build like Gatsby?

At a minimum, the docs should be integrated with Google Webmaster to invalidate the old links and crawl the new ones.

**Comment by ShimiSun** [comment]
@MikeWalrath looks like a good discussion topic

**Comment by ShimiSun** [comment]
@karatechops really like this idea and I would like to hear more from your expertise on it, did you publish on this matter a blog on the hpe dev? it could be a great topic.
@MikeWalrath can follow up with you and Ian on how can attack this one.

**Comment by karatechops** [comment]
@ShimiSun SSR gets very complicated quickly, it would be a long blog post however a multipart blog series may make sense. Something like `SEO + React = ???` 😀

For this implementation, it wouldn't need to be a super fancy setup with traversing component trees. If we want to avoid base refactor we could get by with running a simple Express server to serve [React's output as a string](https://reactjs.org/docs/react-dom-server.html#rendertostring). As long as the site's pages aren't making additional async requests to APIs this could be pretty lean.

**Comment by karatechops** [comment]
I assume this is being hosted on netlify, this is pretty interesting -> https://www.netlify.com/docs/prerendering/

**Comment by ShimiSun** [comment]
link #140
