### ISSUE TITLE
DataTable 

### ISSUE THREAD

**Issue by britt6612** [grommet/grommet-site#80]
I had came across Data Table in the site in Firefox that is now showing the way is intended as the other browsers. Below is the screen shot of how it looks in Chrome followed by the bug screen shot from Fire Fox
![screen shot 2019-02-11 at 4 06 20 pm](https://user-images.githubusercontent.com/42451602/52599837-008ee100-2e17-11e9-9d55-e3d273cfa034.png)

![screen shot 2019-02-11 at 3 56 40 pm](https://user-images.githubusercontent.com/42451602/52599773-d0474280-2e16-11e9-9b57-6fb9d174de4d.png)

**Comment by RohitoOo** [comment]
Hey, @britt6612  I'm having the same cross-browser compatibility issue. The DataTable works fine on chrome and safari but it gets distorted in Firefox just the image above.

How did you solve the issue?

**Comment by britt6612** [comment]
Hey @RohitoOo  I cleared my cache and that is what did it for me. I was messing with the inspect element but after I cleared it then it did not show up again. try that if not feel free to reopen the issue!
