### ISSUE TITLE
Slack icon is showing a privacy error

### ISSUE THREAD

**Issue by MikeWalrath** [grommet/grommet-site#82]
The Slack icon at the bottom of the home page is showing a privacy error. https://slackin.grommet.io/

![image](https://user-images.githubusercontent.com/17712467/52794940-0b6f8e80-302e-11e9-9496-a08b1430f9f2.png)

**Comment by ShimiSun** [comment]
@MikeWalrath To make sure we are on the same page, this is the warning:

![image 2](https://user-images.githubusercontent.com/6320236/52894455-c733d980-3166-11e9-97ba-aad07bd5ea0c.png)

I wonder why it is showing it is not secure when the Certificate only expires on 2020
![screen shot 2019-02-15 at 9 24 13 pm](https://user-images.githubusercontent.com/6320236/52894539-3827c100-3168-11e9-9106-4c80985c9e15.png)

This might be relevant or a good lead, see @bryanjacquot comment:
https://github.com/rauchg/slackin/issues/31

**Comment by MikeWalrath** [comment]
Confirmed. This is the same error I see.

**Comment by sofiageo** [comment]
It looks like the certificate is setup for https://grommet-slackin.herokuapp.com/ - not for https://slackin.grommet.io/

I guess it's setup on heroku? I'm not familiar with it but maybe the solution can be found here: https://devcenter.heroku.com/articles/ssl

**Comment by shivamsingha** [comment]
v2.grommet.io seems to have a wildcard certificate. Why not use that one here?

**Comment by ShimiSun** [comment]
https://grommet.slack.com/archives/C04LMHN59/p1565204459228500

**Comment by jcfilben** [comment]
Closing because the link to the slack invite is not longer showing a certificate/privacy error. I believe this was fixed when the slack invite page was redesigned and the url changed to https://slack-invite.grommet.io/
