### ISSUE TITLE
Broken link in /use

### ISSUE THREAD

**Issue by robinmetral** [grommet/grommet-site#87]
One more issue while I'm at it:

The link to Grommet Icons on https://v2.grommet.io/use is broken, it routes to `https://http//icons.grommet.io//`.

I'd make a PR but I can't find a CONTRIBUTING.md and I'm not sure where you're sourcing your content from :wink:

**Comment by ShimiSun** [comment]
hi @robinmetral! thanks for the feedback, could this be a cache issue? It works well on my client
![screen shot 2019-02-27 at 9 41 30 pm](https://user-images.githubusercontent.com/6320236/53541758-8af26880-3ad8-11e9-893e-1a5bedf73723.png)

Can you please try incognito or clean cache and let me know if it reproduces?

And thanks for the feedback on the contribution readme, feel free to browse our grommet https://github.com/grommet/grommet/blob/master/CONTRIBUTING.md

**Comment by robinmetral** [comment]
Hey @ShimiSun!

Sorry I wasn't very clear: the page isn't broken, it's the link on it to _Grommet Icons_:

![screenshot_2019-02-28 use - grommet](https://user-images.githubusercontent.com/35560568/53546666-39c09400-3b2d-11e9-8bcb-7f5726dc9db3.png)

:slightly_smiling_face:
