### ISSUE TITLE
Add anchors for each prop and theme property

### ISSUE THREAD

**Issue by oorestisime** [grommet/grommet-site#93]
It would be nice to be able to directly link to a component prop or theme value in the documentation.

This will greatly help when pointing people to the documentation and avoid a small step for the user needing to search in the page for what we are referring to. 

Well actually this kind of works https://v2.grommet.io/box#align But i would expect to have a small icon link on the left of the value so that i could get these links easier.

**Comment by ericsoderberghp** [comment]
Did you see the link icon on the right when hovering over a property?

**Comment by oorestisime** [comment]
oh!!! no i didn't. 
i was expecting it on the other side, hehe my bad
