### ISSUE TITLE
First google result for "grommet getting started" broken page

### ISSUE THREAD

**Issue by Funcan** [grommet/grommet-site#94]
If I google "grommet getting started" then the first hit is https://grommet.io/docs/get-started which forwards to https://v2.grommet.io/docs/get-started which is a blank page.

**Comment by ShimiSun** [comment]
from @karatechops c/p 
```
Linking the site to Google Web Master to invalidate some of the stale data and crawl the new stuff is one piece. Proper SSR to generate solid SEO is the other piece.  I would think the SSR piece comes first in the flow.
```
#78

**Comment by ShimiSun** [comment]
from @karatechops 
```
@mikewalrath can we setup a GitHub Project for this in grommet site repo? Then we can divvy it up into tickets
```

**Comment by eyesno** [comment]
Same result for looking up "grommet datetime" -- it results in the very top link being a hybrid url which points to v2.grommet.io but uses /docs/... -- I've had similar results with a handful of controls I searched for.

**Comment by ericsoderberghp** [comment]
I think it would be easy to add redirects inside grommet-site to strip the `/docs` portion.

**Comment by ShimiSun** [comment]
#78

**Comment by sofiageo** [comment]
Same for "grommet mobile" - first result from Google gives https://grommet.io/docs/mobile which redirects to https://v2.grommet.io/docs/mobile/

**Comment by jcfilben** [comment]
Looks like this issue has been fixed. Searching for "grommet getting started", the first link takes you to https://v2.grommet.io/starter and https://grommet.io/docs/get-started redirects to home page.
